version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - charmbracelet
  - davecgh
  - errgroup
  - go-difflib
  - gopkg
  - mattn
  - pmezard
  - stretchr
  - templ
ignoreWords: []
import: []
